Updates to AMY for DFO notebook
cal-adapt/climakitae pull request #139
Opened 2022-12-15 23:49 UTC by nicolejkeeney

Among other things, creates a new, user friendly function for accessing AMY data. Modifies how data is accessed to allow greater flexibility with AMY-related analyses. Renames tmy.py to meteo_yr.py. **BEFORE MERGING TO MAIN, WE WILL NEED TO UPDATE THE EXISTING TMY NOTEBOOK TO RENAME THE FUNCTIONS**

2022-12-16 14:58 UTC, vicford requested changes
Looks like the data location map in the explore AMY panel is shifted to the right? 

![Screen Shot 2022-12-16 at 9 36 00 AM](https://user-images.githubusercontent.com/106171203/208125498-4038c954-aa64-4159-a40c-ca2164fcde2b.png)

While also not necessary, I am wondering whether this might be a good time to also clean up the meteo_yr.py script to switch all remaining instances of "TMY" to "AMY", this will require quite a bit of checking to make sure nothing breaks, food for thought

2022-12-16 14:58 UTC, vicford commented
I also have pushed a PR on the AMY notebook as requested :)

2022-12-16 23:30 UTC, elehmer approved these changes
LGTM!

2022-12-16 23:30 UTC, elehmer commented on climakitae/data_loaders.py
> +        if selections.area_average == "Yes":
Ahh yeah this is different now...

2022-12-17 18:00 UTC, elehmer commented
> Ran through the entire notebook with this climakitae branch loaded in, everything now works as it should with updated language for the notebook in PR [#30](https://github.com/cal-adapt/cae-notebooks/pull/30).
> 
> Looks like the data location map in the explore AMY panel is shifted to the right?
> 
> ![Screen Shot 2022-12-16 at 9 36 00 AM](https://user-images.githubusercontent.com/106171203/208125498-4038c954-aa64-4159-a40c-ca2164fcde2b.png)
> 
> While also not necessary, I am wondering whether this might be a good time to also clean up the meteo_yr.py script to switch all remaining instances of "TMY" to "AMY", this will require quite a bit of checking to make sure nothing breaks, food for thought

Hmm, yeah I'm seeing the offset map as well. Annoying!!

2023-01-03 15:34 UTC, vicford approved these changes

2023-01-03 20:28 UTC, merged