Updates to location map
cal-adapt/climakitae pull request #164
Opened 2023-02-09 03:17 UTC by nicolejkeeney

I made the little location map update better based on your selection, and moved it into a separate object instead of making it a function of LocSelectorArea. I also set up the framework to incorporate the LOCA data into the map (eventually). By moving the view functionality into a different object, the map is able to take the input from app.selections and modify the map based on changes to the data selections. 

**To test**: Try running these 4 panels-- app.select(), app.explore.thresholds(), app.explore.amy(), and app.explore.warming_levels()-- and messing around with the location and resolution selections to make sure the map works well!

2023-02-09 16:10 UTC, vicford requested changes
app.explore.warming_levels map updates quickly

app.explore.amy does not produce a map:
![Screen Shot 2023-02-09 at 10 48 56 AM](https://user-images.githubusercontent.com/106171203/217866140-7d0a94c4-3955-4083-8136-6d43a16cfe87.png)

app.explore.thresholds
Producing same error as app.explore.amy

app.select
Works fine, same as app.explore.warming_levels

All tested on the hub.

2023-02-09 19:47 UTC, nicolejkeeney commented
> app.explore.warming_levels map updates quickly
> 
> app.explore.amy does not produce a map: ![Screen Shot 2023-02-09 at 10 48 56 AM](https://user-images.githubusercontent.com/106171203/217866140-7d0a94c4-3955-4083-8136-6d43a16cfe87.png)
> 
> app.explore.thresholds Producing same error as app.explore.amy
> 
> app.select Works fine, same as app.explore.warming_levels
> 
> All tested on the hub.

Fixed this! Sorry about that.

2023-02-09 20:37 UTC, vicford approved these changes
Looks great!

2023-02-10 18:46 UTC, bethem approved these changes

2023-02-10 19:35 UTC, merged