Timeseries update
cal-adapt/climakitae pull request #201
Opened 2023-04-19 21:54 UTC by thenaomig

This PR addressed two outstanding loose ends in timeseriestools.py
https://trello.com/c/g35VOHPb
and
https://trello.com/c/LRwiznwG

- You can no longer select a resampling window smaller than the time resolution the data is starting with
- You can select min, max, and/or percentile all at once instead of only one at a time.

2023-04-19 22:31 UTC, thenaomig commented
Something I changed is incompatible with how the test is written... looking into it.

2023-04-20 22:39 UTC, nicolejkeeney requested changes
The way you have it coded now will cause an error if the following line of code is run more than once in a notebook: 

```timeseries = tst.Timeseries(my_data)``` 

The error it raises: 
![error](https://user-images.githubusercontent.com/66140951/233498878-46faa381-9207-405b-8393-8c194e7483a1.png)

Looking at the backend code, I think this is because the dictionary `_time_scales` is deleting the keys for days and hourly the first time the `Timeseries` class is used.

The first time I ran this it worked great, though!

2023-04-22 23:03 UTC, thenaomig commented
> The way you have it coded now will cause an error if the following line of code is run more than once in a notebook:
> 
> `timeseries = tst.Timeseries(my_data)`

Should be resolved with latest update.

2023-04-24 16:51 UTC, nicolejkeeney approved these changes
Looks good to me!

2023-04-25 14:27 UTC, vicford approved these changes
This looks great - I really like the compound min/mean/percentile display

2023-04-25 15:36 UTC, elehmer approved these changes
Works great! Just the one code reduction comment...

2023-04-25 20:41 UTC, elehmer commented on climakitae/timeseriestools.py
> +        if _time_resolution == "monthly":
Awesome!

2023-04-25 21:13 UTC, merged