Add features to CSV export
cal-adapt/climakitae pull request #246
Opened 2023-07-03 19:20 UTC by Tianchi-Liu

- warn and name unnamed DataArrays so that they can be exported
- rename columns to ease column access in R (no spaces / special characters, start with a letter or a dot, unique)
- add DataArray variable unit to header if it exists as the `units` attribute
- warn about Excel column limit in addition to row limit

To test: export data in notebooks with export sections.

2023-07-05 16:11 UTC, nicolejkeeney requested changes
I'm unable to unzip the csv file generated by the export function once I download it from the hub to my local drive. 

![cannot_unzip](https://github.com/cal-adapt/climakitae/assets/66140951/9c5e1579-2253-4bfa-9d2a-88e23305e218)

2023-07-05 17:46 UTC, Tianchi-Liu commented on climakitae/data_export.py
> +        )
The Archive Utility error could be due to interruption during file download. Could you try downloading again or unzipping through the Terminal? I was able to unzip on Windows and don't have a Mac to test on.

2023-07-05 18:42 UTC, elehmer reviewed
Looks good. Just the minor comments

2023-07-05 18:42 UTC, elehmer commented on climakitae/data_export.py
> +        )
Yeah I agree, just go ahead and say no filename prefix was given so naming it 'data'.

2023-07-06 15:59 UTC, nicolejkeeney approved these changes
You're right that I can unzip the file using the command line. I think we should think about guidance for our users on how to do so. I don't love that Mac users will encounter this error and be required to understand how to use their command line to access downloaded data. But that isn't related to this PR I'm realizing and could be addressed in a separate PR, so I've approved this one :D

2023-07-07 19:11 UTC, Tianchi-Liu commented on climakitae/data_export.py
> +        data table with the variable unit added to its header
Great catch. Don't trust code editor defaults!

2023-07-07 19:12 UTC, Tianchi-Liu commented on climakitae/data_export.py
> +        )
Yeah I see how the warning can be confusing. Replaced with a comment on why naming is necessary.

2023-07-07 19:28 UTC, merged