Restored retrieval of reanalysis-driven WRF run
cal-adapt/climakitae pull request #254
Opened 2023-07-18 22:41 UTC by thenaomig

This PR fixes degradation introduced in https://github.com/cal-adapt/climakitae/pull/238, after which 'retrieve' failed to return anything for "Historical Reconstruction" (e.g. the reanalysis-driven WRF simulation). 

The structure of the xr.DataArray in which the ERA5_WRF data is returned is different from before when "Historical Climate" and "Historical Reconstruction" are both selected. The "ERA5_WRF" label is appended along the "simulation" dimension, but the scenario dimension is labeled "Historical" to avoid the inefficiency of a sparse array with two values along the 'scenario' dimension.

2023-07-19 14:12 UTC, vicford requested changes
Retrieval of the reconstruction data works as desired, but I have mixed feelings about the differing scenario names based on which combination of data is being selected, and am wondering if we should streamline it further to have just "Historical" as the scenario name regardless of which data product is selected. Potentially a way to ensure that it is clear when both simulation + reanalysis data are selected which is the reanalysis is to append "_Reconstruction" to "WRF_ERA5", but I am aware that will cause other issues within the backend. This doesn't preclude the retrieval piece being merged in though.

2023-07-20 16:41 UTC, thenaomig commented
> When both "Historical Climate" and "Historical Reconstruction" are selected, only Historical Climate is returned. The output data here should have two scenarios, not just one.
> 
> ![only historical climate returned](https://user-images.githubusercontent.com/66140951/254641172-9b66cd43-ca7e-43c0-98dc-e69a39d64047.png)

Yes, this is on purpose. I am changing how it is returned, so that it's not a sparse array. Is there a notebook or other tool that relies on it being the other way?

2023-07-20 18:29 UTC, thenaomig commented
Re-separated "Historical Climate" and "Historical Reconstruction" on scenario dimension to match prior behavior. In future may separate these so they are never returned in one merged object.

Another small fix for when ssps are selected with fewer simulations, so only the relevant historical simulation is returned.

2023-07-21 16:46 UTC, nicolejkeeney approved these changes
Looks good to me!

2023-07-24 14:38 UTC, vicford approved these changes

2023-07-24 20:21 UTC, merged