contributor guidelines draft
cal-adapt/climakitae pull request #293
Opened 2023-11-06 21:57 UTC by gdicecco

I added a draft of some text to populate the Contributor Guidelines page of the readthedocs documentation. To review, follow the instructions in `docs/README` to build the documentation locally and view in your browser. 

I'm open to suggestions on content/formatting/etc.!

2023-11-06 22:02 UTC, claalmve commented on docs/contribute.rst
> +	`Jupyter <https://jupyter.org/>`_ notebooks in python which:
```suggestion
	`Jupyter <https://jupyter.org/>`_ notebooks in Python which: 
```

2023-11-06 22:04 UTC, claalmve commented on docs/contribute.rst
> +Contributions to climakitae that we would welcome could involve a performance improvement, something which makes any of the tools more generally applicable, or adds a feature to handle a commonly-req
```suggestion
Welcomed contributions could involve a performance improvement, something which makes any of the tools more generally applicable, or adds a feature to handle a commonly-requested operation (without duplicating anything that already exists in the Pangeo ecosystem).
```

2023-11-07 14:56 UTC, vicford commented on docs/contribute.rst
> +1. `climakitae <https://github.com/cal-adapt/climakitae>`_ (Climate Kit – Analytics Engine, get it?)
```suggestion
1. The `climakitae <https://github.com/cal-adapt/climakitae>`_ Python library:
```

2023-11-07 15:04 UTC, vicford commented on docs/contribute.rst
> +This is an open-source project, and we welcome contributions from the community.
```suggestion
This is an open-source project, and all contributions, including new feature development, documentation, bug reports, bug fixes, and other ideas are welcome. 
```

2023-11-07 15:05 UTC, vicford commented on docs/contribute.rst
> +	* Specific to the data for the `State of California <https://analytics.cal-adapt.org/data/>`_ that has 	been downscaled based on CMIP6 climate models.
```suggestion
	* Specific to the downscaled CMIP6 climate model data produced for the `State of California <https://analytics.cal-adapt.org/data/>`_ .
```

2023-11-07 15:06 UTC, vicford commented on docs/contribute.rst
> +	* Do a specific analysis for an example use-case or application of the data
```suggestion
	* Perform a specific analysis for an example use-case or application of the data
```

2023-11-07 15:07 UTC, vicford commented on docs/contribute.rst
> +Notebooks should be applications of general interest to our user community, which use the tools in climakitae whenever such a tool exists, and do not have dependencies outside of the `Pangeo librarie
```suggestion
Contributed notebooks should be applications of general interest to our user community, which use the tools in climakitae whenever such a tool exists, and do not have dependencies outside of the `Pangeo libraries <https://github.com/pangeo-data/pangeo-docker-images/blob/master/pangeo-notebook/packages.txt>`_.
```

2023-11-07 15:07 UTC, vicford commented on docs/contribute.rst
> +If you have an idea for a contribution, please employ the following procedure:
```suggestion
If you have an idea for contributing to either climakitae or cae-notebooks, please employ the following procedure:
```

2023-11-07 15:21 UTC, vicford requested changes
Thanks @gdicecco for taking this on! My last comment is more of do we have certain guidelines we want contributions to adhere to, rather than us formatting contributions as they come in.

2023-11-07 15:21 UTC, vicford commented on docs/contribute.rst
> +2. Submit a pull-request to the repository in question for members of our team to review.
Wondering if we also have set documentation etc. requirements that we also want to list here as well

Brainstorming an example below for discussion of how we want to structure contributions:

2a. For climakitae, new functions and features should be sufficiently documented via docstrings
2b. For contributed functionality, we recommend either integrating new code into our existing scripts (e.g., util/utils.py) or introducing new code into a new .py script in either the /tools or /utils folders
2c. Contributed notebooks to cae-notebooks should reside in a new folder housed in the /collaborative folder. We recommend utilizing a descriptive lowercase name for your contributed notebook. Contributed notebooks are requested to follow our notebook structure, consisting of: 
- Brief markdown overview/purpose of notebook, including a section titled "Intended Application" with a brief numbered list of the key take-away points a user will learn from the notebook
- Step 0: package imports
- Step 1: data retrieval and modifications if necessary
- Step 3+: analysis and optional figures
- Concluding Step: export of data object(s)
Our development team will assist with this structure, if you have questions.

2023-11-09 21:40 UTC, vicford approved these changes
Just one small typo, otherwise looks great!

2023-11-09 21:40 UTC, vicford commented on docs/contribute.rst
> +	* For contributed functionality, we recommend either integrating new code into our existing scripts (e.g., ``util/utils.py`` introducing new code into a new .py script in either the ``/tools`` or ``
```suggestion
	* For contributed functionality, we recommend either integrating new code into our existing scripts (e.g., ``util/utils.py``) or introducing new code into a new .py script in either the ``/tools`` or ``/utils`` folders
```

2023-11-09 21:55 UTC, claalmve approved these changes

2023-11-09 23:01 UTC, merged