Re-adding former `generate_gwl_tables.py` file
cal-adapt/climakitae pull request #312
Opened 2024-02-01 22:13 UTC by claalmve

2024-02-02 23:14 UTC, elehmer requested changes

2024-02-02 23:14 UTC, elehmer commented on climakitae/data/gwl_1981-2010ref_debugged.csv
Agreed, not seeing a ref

2024-02-02 23:14 UTC, elehmer commented on climakitae/util/generate_gwl_tables.py
> +            all_wl_data_tbls.to_csv(f"../data/gwl_1850-1900ref_timeidx_{model}.csv")
You can use relative path here `data/gwl...`

2024-02-02 23:14 UTC, elehmer commented on climakitae/util/generate_gwl_tables.py
> +    all_wl_data_tbls.to_csv("../data/gwl_1850-1900ref_timeidx.csv")
relative path

2024-02-02 23:14 UTC, elehmer commented on climakitae/util/generate_gwl_tables.py
> +    # all_wl_data_tbls.to_csv("../data/gwl_1850-1900ref_timeidx.csv")
relative path

2024-02-07 02:25 UTC, claalmve commented on climakitae/explore/agnostic.py
> +    df = pd.read_csv("~/src/climakitae/climakitae/data/gwl_1850-1900ref.csv")
Ignore this `read_csv`, I will fix this tomorrow with the correct relative path reading

2024-02-08 22:21 UTC, elehmer approved these changes
Really hard to review with a lot of the code already merged...there are a couple of comments on the previous commit of agnostic.py that you hopefully see. Let's not do this again lol. Thx

2024-02-12 17:39 UTC, merged