Batch mode wl
cal-adapt/climakitae pull request #403
Opened 2024-07-24 19:18 UTC by claalmve

# Description of PR

**Summary of changes and related issue**

**Relevant motivation and context**

**Dependencies required for this change?**

**Fixes # (issue), delete if not necessary**

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

**Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.**

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-08-06 00:51 UTC, vicford requested changes
Runs all fine and appreciate throwing the new text statement in. What I am noticing is that for WL batch mode turned off the data export of files gets funky in terms of filenames, even though presumably the lat/lons should make these separate? -- screenshot below. 
![Screenshot 2024-08-05 at 7 50 28 PM](https://github.com/user-attachments/assets/b4c7064e-8d43-45d0-8f11-69497bbe7905)

2024-08-07 15:17 UTC, vicford approved these changes

2024-08-07 20:21 UTC, Tianchi-Liu approved these changes
`get_closest_gridcell` is working well with one caveat that, for LOCA, lat lon far from the cached area still outputs data. The issue would be very easy to resolve once crs is defined. In the mean time, consider setting the tolerance to a tiny number in degrees. The change getting the function to no longer error for LOCA is definitely an improvement, so feel free to merge it!

2024-08-08 21:51 UTC, claalmve commented
> `get_closest_gridcell` is working well with one caveat that, for LOCA, lat lon far from the cached area still outputs data. The issue would be very easy to resolve once crs is defined. In the mean time, consider setting the tolerance to a tiny number in degrees. The change getting the function to no longer error for LOCA is definitely an improvement, so feel free to merge it!

Great catch! The tolerance is basically all of the Earth for LOCA data as is. It's now been fixed to have a tolerance adjusted to LOCA lat/lon rather than WRF x/y.

2024-08-08 22:03 UTC, merged