Replace regionmask with rioxarray.clip for masking of data
cal-adapt/climakitae pull request #64
Opened 2022-08-24 21:56 UTC by elehmer

This PR completely removes all dependency on `regionmask` by replacing the remaining calls with `rioxarray.clip`. This particular code is dependent on the changes in #63. `_read_from_catalog` now passes a geometry collection instead of a Region object to `_open_and_concat` where the mask is done with one command! It appears to work just as before and I have not seen much difference in performance, which is unfortunate but at least we have one less non-pangeo dependency.

2022-08-24 21:59 UTC, elehmer commented on climakitae/data_loaders.py
> +        ds_region = [geom]
This is the change from Region to geometry

2022-08-24 21:59 UTC, elehmer commented on climakitae/data_loaders.py
> +        ds_region = [shape]
Change from Region to geometry

2022-08-24 22:00 UTC, elehmer commented on climakitae/data_loaders.py
> +            data = data.rio.clip(geometries=ds_region, crs=4326, drop=True)
This seems to be the only needed operation and it runs as fast as all this other code.

2022-08-24 22:01 UTC, elehmer commented on climakitae/data_loaders.py
> -import regionmask
Removal of final regionmask dependency!

2022-09-06 19:58 UTC, nicolejkeeney requested changes
This PR will cause a conflict with the current version of explore.py, which was written using the regionmask library. The function _get_postage_data from explore.py modified some code from selectors.py to pull data from AWS and then perform spatial subsetting. I'm not sure the best way to go about resolving this conflict, since the explore.py that exists in the PR is the older version from several weeks ago before we built in the warming levels panel.

2022-09-12 20:15 UTC, nicolejkeeney approved these changes

2022-09-12 20:25 UTC, elehmer commented
Merging so that Nicole can adapt to these changes...

2022-09-12 20:25 UTC, merged